// src/pages/About.tsx
const About = () => {
  return (
    <div className="text-secondary text-2xl/snug tracking-wide font-lekton flex flex-col gap-8">
      <p>Born in Poland, 18 years old software developer and student.</p>
      <p>
        My journey with programming started about four years ago with Python,
        however javascript was the first language I truly learned. Nowadays I'm
        mostly working on frontend with Vue.js, React and Tailwindcss, but I am
        constantly learning new technologies and languages.
      </p>
      <p>
        Outside of coding I also enjoy reading, weightlifting and playing the
        guitar.
      </p>
    </div>
  );
};

export default About;

// src/pages/portfolio/about/index.vue
<template>
  <div class="flex justify-center items-center flex-col gap-20">
    <h2 class="text-8xl font-frederica text-center">About me</h2>
    <div class="w-2/3 text-3xl flex flex-col gap-10">
      <p>Born in Poland, 17 years old software developer and student.</p>
      <p>
        My journey with programming started about three years ago with python,
        but I quickly switched to javascriptm, which was the first language is
        got good at. Nowadays, I'm mostly working on front-end, most often with
        Vue.js. However, I'm always open to learning new languages and
        technologies.
      </p>
      <p>
        Outside of coding, I also enjoy reading (classical novels in
        particular), weightlifting and running. Recently, I've also picked up
        playing the guitar.
      </p>
    </div>
  </div>
</template>
