// src/components/Contact.vue
<template>
  <div class="section contact" id="contact">
    <h2>Contact</h2>
    <div class="links">
      <a href="mailto:radoslaw.kaczmarczyk@proton.me">
        <img src="/svgs/email.svg" alt="email" />
      </a>

      <a href="https://www.instagram.com/your.iron.lung/" target="_blank">
        <img src="/svgs/instagram.svg" alt="instagram" />
      </a>

      <a href="https://github.com/radeqq007" target="_blank">
        <img src="/svgs/github.svg" alt="github" />
      </a>

      <a href="https://x.com/wcale_nie_radek" target="_blank">
        <img src="/svgs/x.svg" alt="x" />
      </a>
    </div>
  </div>
</template>

<script setup lang="ts"></script>

<style scoped>
.links {
  margin-block: 2rem;
  display: flex;
  flex-wrap: wrap;
  gap: 4rem;
}

a {
  display: grid;
  place-items: center;
}

img {
  max-height: 4rem;
  filter: brightness(100);
}

@media screen and (max-width: 600px) {
  .links {
    justify-content: center;
  }
}
</style>

// src/components/sections/Contact.tsx
import Badge from "@/components/Badge";
import Section from "@/components/Section";

const ContactSection = () => {
	return (
		<Section className="row-start-2 row-span-3">
			<h1 className="text-text text-xl/6 font-bold">
				Let's start working together!
			</h1>

			<h2 className="text-text text-lg mt-4">Contact Details</h2>

			<a data-cursor="shrink" href="mailto:radoslaw.kaczmarczyk@proton.me">
				<Badge
					text="radoslaw.kaczmarczyk@proton.me"
					className="py-1 hover:bg-highlight hover:text-text"
				/>
			</a>

			<h2 className="text-text text-lg mt-4">Socials</h2>

			<span className="flex flex-col items-start gap-2">
				<a
					data-cursor="shrink"
					href="https://github.com/radeqq007"
					target="_blank"
					rel="noopener"
				>
					<Badge
						text="GitHub"
						className="py-1 hover:bg-highlight hover:text-text"
					/>
				</a>
				<a
					data-cursor="shrink"
					href="https://www.instagram.com/your.iron.lung/"
					target="_blank"
					rel="noopener"
				>
					<Badge
						text="Instagram"
						className="py-1 hover:bg-highlight hover:text-text"
					/>
				</a>
				<a
					data-cursor="shrink"
					href="https://x.com/wcale_nie_radek"
					target="_blank"
					rel="noopener"
				>
					<Badge
						text="X / Twitter"
						className="py-1 hover:bg-highlight hover:text-text"
					/>
				</a>
			</span>

			<h2 className="text-text text-lg mt-4">CV</h2>

			<a
				data-cursor="shrink"
				download
				href="/portfolio/Radosław_Kaczmarczyk.pdf"
			>
				<Badge
					text="Download CV"
					className="py-1 hover:bg-highlight hover:text-text"
				/>
			</a>
		</Section>
	);
};

export default ContactSection;
