// src/components/Nav.vue
<template>
  <nav>
    <a href="#about">About Me</a>
    <a href="#skills">Skills</a>
    <a href="#work">Work</a>
    <a href="#contact">Contact</a>
  </nav>
</template>

<script setup></script>

<style scoped>
nav {
  position: fixed;
  width: 100%;
  top: 6px;
  left: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 2rem;
}

a {
  text-decoration: none;
  font-size: 2rem;
  color: var(--text);
  font-weight: 100;
  text-shadow: 0 0 10px var(--bg);

  transition: color 0.1s ease-in-out;
}

a:hover {
  color: var(--primary);
}
</style>

// src/components/Nav.tsx
const Nav = () => {
  return (
    <nav className="absolute bottom-2 left-0 right-0 flex items-center justify-center font-baloo text-2xl gap-4">
      <a
        href="/portfolio/"
        className="w-40 h-10 rounded-full border-3 border-primary text-primary grid place-items-center hover:bg-primary hover:text-bg transition-colors"
      >
        ABOUT
      </a>
      <a
        href="/portfolio/skills"
        className="w-40 h-10 rounded-full border-3 border-primary text-primary grid place-items-center hover:bg-primary hover:text-bg transition-colors"
      >
        SKILLS
      </a>
      <a
        href="/portfolio/work"
        className="w-40 h-10 rounded-full border-3 border-primary text-primary grid place-items-center hover:bg-primary hover:text-bg transition-colors"
      >
        WORK
      </a>
      <a
        href="/portfolio/contact"
        className="w-40 h-10 rounded-full border-3 border-primary text-primary grid place-items-center hover:bg-primary hover:text-bg transition-colors"
      >
        CONTACT
      </a>
    </nav>
  );
};

export default Nav;
